# Generated by Django 5.2.7 on 2025-10-21 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SvgAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('svg_text', models.TextField(blank=True, help_text='Código SVG sanitizado', verbose_name='SVG Markup')),
                ('svg_file', models.FileField(blank=True, null=True, upload_to='svgs/', verbose_name='Arquivo SVG')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tags', models.TextField(blank=True, help_text='Tags separadas por vírgula', verbose_name='tags')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
            ],
            options={
                'verbose_name': 'SVG Asset',
                'verbose_name_plural': 'SVG Assets',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='UiWikiComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='categoria')),
                ('link_figma', models.TextField(blank=True, verbose_name='link_figma')),
                ('autor', models.CharField(blank=True, max_length=100, verbose_name='autor')),
                ('tags', models.TextField(blank=True, help_text='Tags separadas por vírgula', verbose_name='tags')),
                ('thumbnail_url', models.TextField(blank=True, verbose_name='thumbnail_url')),
                ('data_importacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_importacao')),
            ],
            options={
                'verbose_name': 'Componente UIWiki',
                'verbose_name_plural': 'Componentes UIWiki',
                'ordering': ['-data_importacao'],
            },
        ),
    ]
