# Generated by Django 5.2.7 on 2025-10-22 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SvgFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('title_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(help_text='Conteúdo do arquivo SVG (texto XML)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_public', models.BooleanField(default=False)),
                ('license_required', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svg_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
